Fix config console.
yiisoft/yii-demo pull request #170
Opened 2020-11-10 14:31 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2020-11-10 16:16 UTC, terabytesoftw commented
Before merge: https://github.com/yiisoft/yii-event/pull/9

2020-11-16 12:11 UTC, viktorprogger requested changes

2020-11-16 12:11 UTC, viktorprogger commented on config/providers-web.php
>      ReverseBlockMerge::class => new ReverseBlockMerge(),
Is it necessary?

2020-11-16 12:13 UTC, viktorprogger commented
There are some more config arrays with an only `ReverseBlockMerge` element. Can we remove that element in this PR?

2020-11-16 12:48 UTC, samdark approved these changes

2020-11-16 12:48 UTC, samdark commented on config/providers-web.php
>      ReverseBlockMerge::class => new ReverseBlockMerge(),
Yes.

2020-11-16 12:50 UTC, merged