Add visual indicator to labels of required fields
yiisoft/yii-demo pull request #202
Opened 2020-12-16 12:04 UTC by Mister-42

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

2020-12-16 16:13 UTC, Mister-42 commented
Test on contact page: this change works, but there are empty labels on the page. These are now made visible by the presence of a red star.
`<label class="control-label control-label required" for="contactform-subject"></label>`

Investigating

2020-12-21 21:28 UTC, samdark requested changes

2020-12-21 21:28 UTC, samdark commented on src/Contact/ContactForm.php
> +            'username' => 'Name',
```suggestion
            'name' => 'Name',
```

2020-12-21 21:28 UTC, samdark commented on views/layout/main.php
> +        label.required:not(:empty):after {
It's better to place it into `site.css`.

2020-12-21 23:03 UTC, merged

2020-12-21 23:03 UTC, samdark commented
👍